# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest stable version

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4  # Updated to latest stable version

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2  # Latest stable version

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2  # Latest stable version
